spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:shop
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

generate:
  data: true
